services:
  - type: web
    name: mon-projet-django
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn mon_projet.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mon_projet.settings
      - key: PYTHON_VERSION
        value: 3.10.12
    plan: free