services:
  - type: web
    name: SITE_PRATIQUE_COLO
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn mon_projet.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mon_projet.settings
      - key: PYTHON_VERSION
        value: 3.10
    plan: free

staticSites:
  - name: static
    buildCommand: ""
    publishPath: static

# Optionnel : pour s'assurer que le fichier SQLite est conservé
# Ajouter un volume pour persister le fichier db.sqlite3
volumes:
  - name: django-sqlite-db
    mountPath: /var/data
    sizeGB: 1

# Ajouter la variable d'environnement pour utiliser ce chemin
# dans votre settings.py :
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': '/var/data/db.sqlite3',
#     }
# }

