services:
  - type: web
    name: site-vente
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn site-vente.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: site-vente.settings
      - key: PYTHON_VERSION
        value: 3.10.12
    plan: free