# Generated by Django 5.1.4 on 2025-02-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insertion_membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=250)),
                ('mot_de_passe', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='static/image/membre')),
            ],
        ),
    ]
