# Generated by Django 5.1.4 on 2025-01-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='insertion_produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('prix', models.FloatField()),
                ('photo', models.ImageField(upload_to='static/image')),
                ('type', models.CharField(max_length=250)),
            ],
        ),
    ]
