# Generated by Django 5.1.4 on 2025-01-28 04:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accueil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertion_produit',
            name='photo2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insertion_produit',
            name='photo3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/image'),
            preserve_default=False,
        ),
    ]
