# Generated by Django 5.1.4 on 2025-02-18 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommenteMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pro', models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_accueil.insertion_produit'))),
                ('id_membre', models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_membre.insertion_membre'))),
                ('commentaire', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
