# Generated by Django 5.1.4 on 2025-02-11 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_membre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Produit', models.TextField()),
                ('id_stripe', models.TextField()),
                ('date_paiement', models.DateTimeField()),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_membre.insertion_membre')),
            ],
        ),
    ]
